export const LOGOUT = 'LOGOUT'
export const SAVE_TOKEN = 'SAVE_TOKEN'
export const FETCH_USER = 'FETCH_USER'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'
export const UPDATE_USER = 'UPDATE_USER'
//
export const REGISTER_ERRORS = 'REGISTER_ERRORS'


//TASKS
export const FETCH_TASKS = 'FETCH_TASKS'
export const FETCH_TASKS_FAILURE = 'FETCH_TASKS_FAILURE'
export const FETCH_STATUSES_FAILURE = 'FETCH_STATUSES_FAILURE'
export const FETCH_STATUSES = 'FETCH_STATUSES'

//developers
export const FETCH_DEVELOPERS_FAILURE = 'FETCH_DEVELOPERS_FAILURE'
export const FETCH_DEVELOPERS = 'FETCH_DEVELOPERS'
export const FETCH_ERRORS = 'FETCH_ERRORS'
export const FETCH_ALL_DEVELOPERS_FAILURE = 'FETCH_ALL_DEVELOPERS_FAILURE'
export const FETCH_ALL_DEVELOPERS = 'FETCH_ALL_DEVELOPERS'